# Generated by Django 5.1.7 on 2025-03-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_and_time', models.CharField(help_text='г. Набережные Челны, ул. Шамиля Усманова, д.19. Время проведения: с 09:30', max_length=100, verbose_name='адрес и время проведения')),
                ('number_of_people', models.CharField(help_text='100', max_length=100, verbose_name='количество людей')),
                ('date', models.CharField(help_text='15 июня 2023', max_length=100, verbose_name='дата')),
                ('price_in_figures', models.CharField(help_text='17 000', max_length=100, verbose_name='цена(цифрами)')),
                ('price_in_words', models.TextField(help_text='семнадцать тысяч', max_length=100, verbose_name='цена(словами)')),
                ('time', models.CharField(help_text='09:30-10:30', max_length=100, verbose_name='время проведения')),
                ('act_and_account_number', models.CharField(help_text='50/1 от 15 июня 2023 г.', max_length=100, verbose_name='номер акта и счета')),
                ('number_basis_of_the_contract', models.CharField(help_text='Nº 50/23-11 от 18.05.2023 г.', max_length=100, verbose_name='номер основание договора')),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Индивидуальный предприниматель Мотыгуллин Айрат Маратович', max_length=100, verbose_name='Название организации')),
                ('requisites', models.TextField(help_text='ООО «Алгарыш»423822, Республика Татарстан, г. Набережные Челны, проспект Чулман, д. 8, пом. 4ИНН 1650343159 ...', max_length=10000, verbose_name='Реквизиты')),
                ('fio', models.TextField(help_text='А.М. Мотыгуллин, И.Ф. Шайхутдинов', max_length=100, verbose_name='ФИО руководителя')),
                ('inn', models.CharField(help_text='165204115017', max_length=100, verbose_name='ИНН')),
                ('bik', models.CharField(help_text='044525104', max_length=100, verbose_name='БИК')),
                ('bank_name', models.TextField(help_text='ООО «Банк Точка»', max_length=100, verbose_name='Имя банка')),
                ('short_name', models.TextField(help_text='ИП Мотыгуллин Айрат Маратович', max_length=100, verbose_name='Короткое имя')),
                ('correspondent_bank_account', models.CharField(help_text='30101810745374525104', max_length=100, verbose_name='кор. счет')),
                ('bank_account', models.CharField(help_text='40802810101500493834', max_length=100, verbose_name='Р/С')),
                ('kpp', models.CharField(help_text='165001001', max_length=100, verbose_name='КПП')),
                ('address', models.CharField(help_text='423822, Республика Татарстан, г. Набережные Челны, проспект Чулман, д. 8, пом. 4', max_length=200, verbose_name='Адрес')),
            ],
        ),
    ]
