# Generated by Django 5.1.7 on 2025-04-05 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Муниципальное бюджетное общеобразовательное учреждение «Гимназия №54», в лице директора Исаева Рамиля РобертовичаИндивидуальный предприниматель Мотыгуллин Айрат Маратович, действующего на основании ОГРНИП №323169000037033/', max_length=1000, verbose_name='Название организации полностью')),
                ('requisites', models.TextField(help_text='ООО «Алгарыш»423822, Республика Татарстан, г. Набережные Челны, проспект Чулман, д. 8, пом. 4ИНН 1650343159 ...', max_length=10000, verbose_name='Реквизиты (Карта партенра)')),
                ('fio', models.TextField(help_text='А.М. Мотыгуллин, И.Ф. Шайхутдинов', max_length=100, verbose_name='ФИО руководителя')),
                ('function', models.CharField(choices=[('DIRECTOR', 'Директор'), ('ENTREPRENEUR', 'Индивидуальный предприниматель')], max_length=100, verbose_name='Должность')),
                ('inn', models.CharField(help_text='165204115017', max_length=100, verbose_name='ИНН')),
                ('bik', models.CharField(help_text='044525104', max_length=100, verbose_name='БИК')),
                ('bank_name', models.TextField(help_text='ООО «Банк Точка»', max_length=100, verbose_name='Имя банка')),
                ('short_name', models.TextField(help_text='ИП Мотыгуллин Айрат Маратович', max_length=100, verbose_name='Короткое имя')),
                ('correspondent_bank_account', models.CharField(help_text='30101810745374525104', max_length=100, verbose_name='кор. счет')),
                ('bank_account', models.CharField(help_text='40802810101500493834', max_length=100, verbose_name='Р/С')),
                ('kpp', models.CharField(help_text='165001001', max_length=100, verbose_name='КПП')),
                ('address', models.TextField(help_text='423822, Республика Татарстан, г. Набережные Челны, проспект Чулман, д. 8, пом. 4', max_length=200, verbose_name='Адрес')),
                ('is_our', models.BooleanField(default=False, verbose_name='Наша организация?')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Проведение культурно-массового мероприятия: "Соревнования роботов"', max_length=200, verbose_name='Название услуги')),
                ('date', models.CharField(help_text='28.05.2025 г.', max_length=15, verbose_name='Срок оказания услуг')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_and_time', models.CharField(help_text='(<i>г. Набережные Челны, ул. Шамиля Усманова, д.19. Время проведения: с 09:30</i>)', max_length=100, verbose_name='адрес и время проведения')),
                ('date', models.CharField(help_text='(<i>15 июня 2023</i>)', max_length=100, verbose_name='дата')),
                ('price_in_figures', models.CharField(help_text='(<i>17 000</i>)', max_length=100, verbose_name='цена(цифрами)')),
                ('price_in_words', models.CharField(help_text='(<i>семнадцать тысяч рублей 00 копеек</i>)', max_length=100, verbose_name='цена(словами)')),
                ('time', models.CharField(help_text='(<i>09:30-10:30</i>)', max_length=100, verbose_name='время проведения')),
                ('act_and_account_number', models.CharField(help_text='(<i>50/1 от 15 июня 2023 г.</i>)', max_length=100, verbose_name='номер акта и счета с датой')),
                ('number_basis_of_the_contract', models.CharField(help_text='(<i>Nº 50/23-11 от 18.05.2023 г.</i>)', max_length=100, verbose_name='номер основание договора')),
                ('viewers', models.CharField(help_text='180 (Сто восемьдесят)', max_length=50, verbose_name='Кол-во зрителей ')),
                ('customer', models.ForeignKey(limit_choices_to={'is_our': False}, on_delete=django.db.models.deletion.CASCADE, related_name='documents_as_customer', to='main.organisation', verbose_name='Заказчик (не мы)')),
                ('doer', models.ForeignKey(limit_choices_to={'is_our': True}, on_delete=django.db.models.deletion.CASCADE, related_name='documents_as_doer', to='main.organisation', verbose_name='Исполнитель (мы)')),
                ('services', models.ManyToManyField(related_name='document', to='main.service', verbose_name='Услуги')),
            ],
        ),
        migrations.CreateModel(
            name='ViewerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewers', models.IntegerField(help_text='100', verbose_name='Кол-во зрителей')),
                ('price', models.FloatField(help_text='200.5', verbose_name='Цена за единицу')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewer_categories', to='main.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Категория зрителей',
                'verbose_name_plural': 'Категории зрителей',
            },
        ),
    ]
