# Generated by Django 5.1.7 on 2025-04-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='function',
            field=models.CharField(choices=[('Директор', 'Директор'), ('Индивидуальный предприниматель', 'ИП')], max_length=100, verbose_name='Должность'),
        ),
    ]
