# Generated by Django 5.1.7 on 2025-04-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_organisation_function'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='act_and_account_number',
            field=models.CharField(help_text='(<i>50/1</i>)', max_length=100, verbose_name='номер акта'),
        ),
        migrations.AlterField(
            model_name='document',
            name='address_and_time',
            field=models.CharField(help_text='(<i>г. Набережные Челны, ул. Шамиля Усманова, д.19. Время проведения: с 09:30</i>)', max_length=150, verbose_name='адрес и время проведения'),
        ),
    ]
