# Generated by Django 5.1.7 on 2026-05-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_document_act_and_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='number_basis_of_the_contract',
            field=models.CharField(help_text='(<i>50/23-11</i>)', max_length=100, verbose_name='номер основание договора'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='short_name',
            field=models.TextField(help_text='Муниципальное бюджетное общеобразовательное учреждение «Гимназия №54»', max_length=100, verbose_name='Короткое имя'),
        ),
    ]
